name: searchtosu
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  sqflite: ^1.3.1
  after_layout: ^1.0.7+2
  clipboard_manager: ^0.0.4
  android_intent: ^0.3.6+12
  permission_handler: ^4.4.0+hotfix.2
  shared_preferences: ^0.5.7+3
  dropdown_formfield: ^0.1.2
  flutter_speed_dial: ^1.2.5
  animations: ^1.1.1
  audioplayers: ^0.15.1
  adhan_flutter: ^0.0.4
  flutter_native_timezone: ^1.0.4
  toast: ^0.1.5
  animated_text_kit: ^2.2.0
  flutter_map: ^0.10.1
  path_provider: ^1.6.11
  matrix_gesture_detector: ^0.1.0
  geolocator: ^5.3.2+2
  provider: ^4.3.1
  dropdownfield: ^1.0.3
  intl: ^0.16.1
  flutter_local_notifications: ^1.3.0
  hijri: ^2.0.2
  bangla_utilities: ^0.1.1
  http: ^0.12.1
  google_maps_flutter: ^0.5.28+1
  compasstools: ^0.1.0
  hijri_picker: ^2.0.0
  cloud_firestore: ^0.13.7
  share: ^0.6.4+3
  url_launcher: ^5.5.0
  geocoder: ^0.2.1
  deivao_drawer: ^1.0.0+6
  webview_flutter: ^0.3.22+1
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "images/app_logo1.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Maddina
      fonts:
        - asset: fonts/maddina.ttf
    - family: Monserat
      fonts:
        - asset: fonts/Monserat.ttf
    - family: Mukadimah
      fonts:
        - asset: fonts/Mukadimah.ttf
    - family: QalamMajid
      fonts:
        - asset: fonts/QalamMajid.ttf
    - family: utman
      fonts:
        - asset: fonts/Uthman.ttf
    - family: mequran
      fonts:
        - asset: fonts/me_quran.ttf
    - family: kalpurus
      fonts:
        - asset: fonts/Kalpurush.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
